###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

services:
    reverse-proxy:
      image: nginx:alpine
      container_name: study-planner-reverse-proxy
      volumes:
        - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
      ports:
      - "7070:80"

    api-webserver:
      image: nginx:alpine
      container_name: study-planner-api-webserver
      working_dir: /application
      volumes:
          - ./api:/application
          - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    api-php-fpm:
      build: api/docker/php-fpm
      container_name: study-planner-api-php-fpm
      working_dir: /application
      volumes:
        - ./api:/application
        - ./api/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    webapp:
      build: webapp/docker
      container_name: study-planner-webapp
      working_dir: /application
      volumes:
        - ./webapp:/application
