###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    api-webserver:
      image: nginx:alpine
      container_name: study-planner-api-webserver
      working_dir: /application
      volumes:
          - ./api:/application
          - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9090:80"

    api-php-fpm:
      build: api/docker/php-fpm
      container_name: study-planner-api-php-fpm
      working_dir: /application
      volumes:
        - ./api:/application
        - ./api/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

