plan_create_pdf:
    path: '/plan/create/pdf'
    defaults: { _controller: 'StudyPlanner\Infrastructure\Controller\CreatePDFPlanController' }

plan_create_ics:
    path: '/plan/create/ics'
    defaults: { _controller: 'StudyPlanner\Infrastructure\Controller\CreateICSPlanController' }
