#index:
#    path: /
#    controller: App\Controller\DefaultController::index


plan_create:
    path: '/plan/create'
    defaults: { _controller: 'StudyPlanner\Infrastructure\Controller\CreatePlanController' }
